/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ConsumeExample {
    }
    interface ProvideExample {
        "section": string;
    }
}
declare global {
    interface HTMLConsumeExampleElement extends Components.ConsumeExample, HTMLStencilElement {
    }
    var HTMLConsumeExampleElement: {
        prototype: HTMLConsumeExampleElement;
        new (): HTMLConsumeExampleElement;
    };
    interface HTMLProvideExampleElement extends Components.ProvideExample, HTMLStencilElement {
    }
    var HTMLProvideExampleElement: {
        prototype: HTMLProvideExampleElement;
        new (): HTMLProvideExampleElement;
    };
    interface HTMLElementTagNameMap {
        "consume-example": HTMLConsumeExampleElement;
        "provide-example": HTMLProvideExampleElement;
    }
}
declare namespace LocalJSX {
    interface ConsumeExample {
    }
    interface ProvideExample {
        "section"?: string;
    }

    interface ProvideExampleAttributes {
        "section": string;
    }

    interface IntrinsicElements {
        "consume-example": ConsumeExample;
        "provide-example": Omit<ProvideExample, keyof ProvideExampleAttributes> & { [K in keyof ProvideExample & keyof ProvideExampleAttributes]?: ProvideExample[K] } & { [K in keyof ProvideExample & keyof ProvideExampleAttributes as `attr:${K}`]?: ProvideExampleAttributes[K] } & { [K in keyof ProvideExample & keyof ProvideExampleAttributes as `prop:${K}`]?: ProvideExample[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "consume-example": LocalJSX.IntrinsicElements["consume-example"] & JSXBase.HTMLAttributes<HTMLConsumeExampleElement>;
            "provide-example": LocalJSX.IntrinsicElements["provide-example"] & JSXBase.HTMLAttributes<HTMLProvideExampleElement>;
        }
    }
}
